version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: asda_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: asda_web
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn ASDAsite.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./static:/static 
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: asda_db